version: '3.8'

services:
  # MySQL Container
  mysql:
    image: mysql:5.6
    container_name: orange-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: orangehrm
      MYSQL_DATABASE: orangehrm
      MYSQL_USER: orangehrm
      MYSQL_PASSWORD: orangehrm
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
  # Your Application Container
  app:
    image: musketeers/orangehrm:latest
    container_name: orange-container
    restart: always
    depends_on:
      - mysql
    links:
      - mysql
    ports:
      - "8080:80"
    volumes:
      -  app-data:/var/www/html

volumes:
  mysql-data:
  app-data:
